### ISSUE TITLE
CocoaPods install error (could not find compatible versions for pod "mobile_scanner"

### ISSUE THREAD

**Issue by JakeCallery** [juliansteenbakker/mobile_scanner#1245]
Hey, firstly, thank you for the great library!

While running pod install in the ios directory of my flutter app, I am getting:
```
[!] CocoaPods could not find compatible versions for pod "mobile_scanner":
  In Podfile:
    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`)

Specs satisfying the `mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`)` dependency were found, but they required a higher minimum deployment target.
```

In XCode I have set the minimum deployment target to iOS 15.5 and and ios deployment target to 15.5 in build settings.
I am using XCode version 15.4, on a M2 Mac Studio running sonoma 14.5

I have also tried setting the deployment versions to 16 and over, but that didn't seem to help.

Any thoughts would be greatly appreciated, or if you need more info from me, please let me know I would be happy to provide.
Thank you!

Attached is my pubspec file.
[pubspec.txt](https://github.com/user-attachments/files/17877400/pubspec.txt)

Not that it is super relevant, but it runs great on Android.

**Comment by Clon1998** [comment]
Can you post the content of your `Podfile`?

At the very top of mine I had:
```
# Uncomment this line to define a global platform for your project
platform :ios, '13.5' # <.------ change to 15.5
```

**Comment by navaronbracke** [comment]
@JakeCallery This requirement was due to a change in MLKit. Fortunately, the beta release for version 7.0.0 removes that requirement. If that works for you, please try that. It is just unfortunate on the MLKit side to have changed the minium so harsly. 

According to the message, it is due to your minimum deployment target not being high enough.

You'll have to change that in several places for it to work, though. For example, I usually have to define it for all my dependencies in the Podfile (`platform :ios` isn't sufficient iirc?)

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end
end
```

Deleting your Podfile.lock could also help?
