### ISSUE TITLE
Detection of QR-Codes not working on Samsung A23 5G

### ISSUE THREAD

**Issue by tim-olbrich** [juliansteenbakker/mobile_scanner#698]
Hello currently I am developing an app for android and iOS and this library works great and is really fast when detecting a QR Code. So kudos for this package. But i have one problem. On the Samsung A23 5G the scanner does not detect a code at all. I have some ideas about the cause of the problem but i have to check. 

So here are some informations about my usage:

# Device:
Samsung Galaxy A23 5G
Android 13

# Flutter Version:
3.10.6

# Package Version:
3.3.0

# Issue:
Detection not working

# Additional Information:
- Working on Galaxy A21, looks like a problem with this specific device.
- Camera stream is visible in the app.

# Assumptions:
- Set Resolution to max (I've read, that this could be a problem with the ml lib from google [https://github.com/flutter-ml/google_ml_kit_flutter/issues/285](google_ml_kit_flutter)
- Using wrong camera (The A23 has 4 different cameras on the back)
- Maybe the image stream is rotated

I am willing to help with this problem if i can get additional information or if someone has experienced similar problems with the same or different devices.

Thank you for your hard work on this library!

**Comment by guagnelz** [comment]
I noticed that works with front camera (only as workaround)

**Comment by tim-olbrich** [comment]
On the A23? I've tried this as well but without success. But I will try it again later today. Thank you!

**Comment by guagnelz** [comment]
Our customer noticed that and after advised to use front camera he succeded to work: device is a SM-A236B

**Comment by pupubird** [comment]
Same goes to Xiaomi 11

**Comment by guagnelz** [comment]
I tried on Xiaomi 11T (21081111RG) and works well

**Comment by rmyr** [comment]
Any idea on what the root cause may be?

**Comment by tim-olbrich** [comment]
No. I have no time to dig into this problem at the moment. But did anyone tried if it works with the newest release? 3.4.1?

**Comment by rmyr** [comment]
I actually experience the same problem in React Native, using [react-native-vision-camera](https://github.com/mrousavy/react-native-vision-camera), which is allowing you to use plugins to process frames (e.g. to look for QR-Codes).

After some debugging I saw that the images that the frame processor receives actually look like this:

**Samsung A32** (QR-Code scanning is working fine, image is blurry cause of first frame while debugging I assume):
![A32](https://github.com/juliansteenbakker/mobile_scanner/assets/12714047/b8b291c6-b41a-4414-a2c5-3b60a78a54a8)

**Samsung A23**:
![A23](https://github.com/juliansteenbakker/mobile_scanner/assets/12714047/17b905ec-b2e1-4dae-8b47-df6d365b2a31)

I don't know if this translates to this library as well. It is a strange coincidence that the same problem appears though, so maybe it is the same root cause. Hope this helps in some way.

**Comment by gunnardag** [comment]
I'm also having issues  with two Samsung devices.
Samsung S20 Ultra & S10 lite.

They work sometimes but seem to stop working after a bit.

Also dragging the notification bar down makes the camera go white screen.

I  have a feeling that these two problems are connected, something with the notification bar on these samsung devices that's interrupting something with the android lifecycle.

**Comment by dasprasky** [comment]
I'm facing the same issue on Samsung A23. It does not detect the QR code. My app is already on production so other devices are working fine but customers with Samsung A23 are facing this issue

**Comment by timbotimbo** [comment]
This appears to be caused by the output of the camera.
Similar issues mentioning this device (together with camera or MLKit) seem to resolve this by using the nv21 image format on android.

Corrupt camera stream: 
https://github.com/flutter/flutter/issues/118350
A23 needs NV21: 
https://github.com/flutter-ml/google_ml_kit_flutter/issues/287#issuecomment-1549828057
https://github.com/flutter-ml/google_ml_kit_flutter/issues/285

If this is indeed the problem, this requires a fix in the plugin code, not something a user can change in their config.

I already see some nv21 references in this plugin, but I don't know this plugin well enough to see which format is used for an android device that I don't have.

**Comment by ViniciusSossela** [comment]
> This appears to be caused by the output of the camera. Similar issues mentioning this device (together with camera or MLKit) seem to resolve this by using the nv21 image format on android.
> 
> Corrupt camera stream: [flutter/flutter#118350](https://github.com/flutter/flutter/issues/118350) A23 needs NV21: [flutter-ml/google_ml_kit_flutter#287 (comment)](https://github.com/flutter-ml/google_ml_kit_flutter/issues/287#issuecomment-1549828057) [flutter-ml/google_ml_kit_flutter#285](https://github.com/flutter-ml/google_ml_kit_flutter/issues/285)
> 
> If this is indeed the problem, this requires a fix in the plugin code, not something a user can change in their config.
> 
> I already see some nv21 references in this plugin, but I don't know this plugin well enough to see which format is used for an android device that I don't have.

@juliansteenbakker

**Comment by ViniciusSossela** [comment]
Hey guys.

I have made some changes on the code, and it seems to now be working on our device models A3 that didn't work before.

Could you try to scan a QRCODE on your device too?

if it works on your devices too, I am gonna open a PR

Just point the mobile_scanner to my forked version
```
  mobile_scanner:
    path: ../mobile_scanner
    # git: git@github.com:ViniciusSossela/mobile_scanner.git
```

**Comment by tim-olbrich** [comment]
Thank you for your effort! Sadly it's still not working on the A23. I just tested your package in our app.

**Comment by ViniciusSossela** [comment]
> Thank you for your effort! Sadly it's still not working on the A23. I just tested your package in our app.

Did you tryed to identify what happens on the native android side of the package on your device?

**Comment by nirbar89** [comment]
Any one test version 3.5.1

**Comment by nirbar89** [comment]
> One of our user has just noticed an issue on this device, so it might be still an issue. Our version: mobile_scanner: 3.5.4
> 
> <img alt="image" width="1199" src="https://private-user-images.githubusercontent.com/33902750/287464071-0be61fcc-71fe-4350-a2a5-db07c0f7ae54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MTIzMTksIm5iZiI6MTcwMTYxMjAxOSwicGF0aCI6Ii8zMzkwMjc1MC8yODc0NjQwNzEtMGJlNjFmY2MtNzFmZS00MzUwLWEyYTUtZGIwN2MwZjdhZTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE0MDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNjBkNzU0ZDM0YTU5NTkyMGU5ZjcxNGJkNjEzYTg1MGU3YTM4OWE2ZDVlM2UzMzAyOGEzYmJhMmRmMjc4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hcNR1oVwCQu63jwMVim2RNTONVsLnOShlVS7bUPseTo">

A temporary solution for us was to set camera resolution to something above the default but a better solution should be found.

**Comment by qwadrox** [comment]
> > One of our user has just noticed an issue on this device, so it might be still an issue. Our version: mobile_scanner: 3.5.4
> > <img alt="image" width="1199" src="https://private-user-images.githubusercontent.com/33902750/287464071-0be61fcc-71fe-4350-a2a5-db07c0f7ae54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2MTIzMTksIm5iZiI6MTcwMTYxMjAxOSwicGF0aCI6Ii8zMzkwMjc1MC8yODc0NjQwNzEtMGJlNjFmY2MtNzFmZS00MzUwLWEyYTUtZGIwN2MwZjdhZTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDE0MDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNjBkNzU0ZDM0YTU5NTkyMGU5ZjcxNGJkNjEzYTg1MGU3YTM4OWE2ZDVlM2UzMzAyOGEzYmJhMmRmMjc4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hcNR1oVwCQu63jwMVim2RNTONVsLnOShlVS7bUPseTo">
> 
> A temporary solution for us was to set camera resolution to something above the default but a better solution should be found.

What resolution did you use? 

Our user gave more information and indeed camera is being initialised but it does not detect.

**Comment by qwadrox** [comment]
Apparently, after setting resolutions manually solved for us. 
We used: 
height 4000
width 3000

@juliansteenbakker Is the new ResolutionSelector improvement on the version [3.5.6](https://pub.dev/packages/mobile_scanner/changelog#356) aims to solve this issue as well? Isn't it?

**Comment by Lars-Sommer** [comment]
Facing the same problem on Samsung A23.

**Comment by theamorn** [comment]
I am encountering the same issue with the Samsung A23. My team decided to purchase a Samsung A23 for me to conduct testing. I took screenshots using mobile_scanner version 3.5.6.

Here are the results from a regular phone:
![617](https://github.com/juliansteenbakker/mobile_scanner/assets/6716483/1412f911-18af-4193-807a-142f8f6d1161)
![618](https://github.com/juliansteenbakker/mobile_scanner/assets/6716483/35bfa6ee-6357-4384-82ed-b222555e215a)

and From Samsung A23
![IMG20244317024317](https://github.com/juliansteenbakker/mobile_scanner/assets/6716483/946b5392-7e46-4b0b-8350-03a2a95c498e)
![IMG20244320024320](https://github.com/juliansteenbakker/mobile_scanner/assets/6716483/efa8a474-a4c8-4ad9-b899-cf87266fb1d9)

I ensured that the camera distance between the two devices was the same (as shown in the first image) and moved in to position the QR code in the middle of the screen (as shown in the second image).

The problem seems to be that the Samsung A23 zooms in by itself. I retrieved these images by including the saving image code into the Gallery in MobileScanner.kt at line 80 using the captureOutput variables.

To address this issue, I find it strange that the default resolution is 640 x 480 and appears to be broken on the Samsung A23. Therefore, I suggest setting the cameraResolution explicitly in the MobileScannerController. For example, I just set it to Size(640, 480) that's it and it's work!!

Behind the scenes, this will set the resolution in Android and avoid using the default resolution, which seems to be causing the problem.

Hope this help

**Comment by navaronbracke** [comment]
I think we do always use YUV and not NV21, per the comment in https://github.com/juliansteenbakker/mobile_scanner/blob/b3e5b58660dc78a9e527854fe209e44f32e20b38/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScanner.kt#L68 and the conversion code that is applied for YUV.

@juliansteenbakker Do you remember why we were using YUV on Android? Specifically for the Samsung device that is affected here, we need NV21. I would investigate if we can just switch to NV21 on Android and drop the YUV format there.
