### ISSUE TITLE
Export MobileScannerArguments Type

### ISSUE THREAD

**Issue by DevNico** [juliansteenbakker/mobile_scanner#7]
Would be great if you could export the MobileScannerArguments type used in the `onDetect` callback.

**Comment by juliansteenbakker** [comment]
That's a good idea! I'm still thinking about how we can pass these arguments, since the parameters of these arguments generally don't change. I don't think we need to pass them on every `onDetect` call, so i'm thinking more of a `onInit` function that only get's called once when initialising the plugin.
