### ISSUE TITLE
`updateScanWindow` does not complete on MacOS and Android

### ISSUE THREAD

**Issue by shareefhadid** [juliansteenbakker/mobile_scanner#730]
I am really struggling with this package :/.

I have an overlay with a cutout, and I am trying to set the scan window for the scanner to match it.

The position of the cutout is dynamic, so I need to calculate the `Rect` for the `scanWindow` once the `RenderBox` of the cutout becomes available.

I have tried the following methods:
- Setting the `scanWindow` property to a function which returns a `Rect` based on the `RenderBox` of the cutout once it is available (i.e. after the first build of the overlay), and returning `null` if it is not available (I added a post frame callback in the overlay builder with `setState()` to make it rebuild)
- Using `barcode.corners` instead of the actual `scanWindow` along with `Rect.contains()`. This didn't work for me (I am assuming because of distortions). The corners I would get back would sometimes contain coordinates outside of the device's width or height.
- Calling `controller.updateScanWindow()` inside the overlay builder once the cutout context is available. In this case, the `Future` would never complete.

I would appreciate any feedback or suggestions on what I can do. I've spent a long time trying different workarounds. I really appreciate the effort put into this package, I hope this doesn't come off as unappreciative, it just hasn't worked as expected for me.

Here is a snippet of my attempt with `updateScanWindow()`:
```dart
overlay: Builder(builder: (context) {
          WidgetsBinding.instance.addPostFrameCallback(
            (_) async {
              final windowBox = _scannerWindowKey.currentContext
                  ?.findRenderObject() as RenderBox;
              final windowPosition = windowBox.localToGlobal(Offset.zero);

              final scanWindow = Rect.fromLTWH(
                windowPosition.dx,
                windowPosition.dy,
                windowBox.size.width,
                windowBox.size.height,
              );
              try {
                await _controller.updateScanWindow(scanWindow);
                logger.i("Scan window set: $scanWindow");
              } catch (e) {
                logger.e("Unalbe to set scan window : $e");
              }
            },
          );
    // ...
  });

**Comment by navaronbracke** [comment]
Hi @shareefhadid you are right with `_controller.updateScanWindow` not completing. This is a bug.

Let me explain what happens.

We pass the scan window to native here: https://github.com/juliansteenbakker/mobile_scanner/blob/da34970567a64fdf66a7df23963a40bc215d9d18/lib/src/mobile_scanner_controller.dart#L484-L491

Now it depends on the platform what we do next. (bear with me for a bit)

On web, setting the scan window is not supported yet, so we return a Future:
https://github.com/juliansteenbakker/mobile_scanner/blob/da34970567a64fdf66a7df23963a40bc215d9d18/lib/mobile_scanner_web_plugin.dart#L63-L64

On iOS we handle the incoming method here:
https://github.com/juliansteenbakker/mobile_scanner/blob/da34970567a64fdf66a7df23963a40bc215d9d18/ios/Classes/MobileScannerPlugin.swift#L222-L227

Notice that we receive the FlutterResult and _call result(nil) at the end_.

On MacOS we handle the method here: 
https://github.com/juliansteenbakker/mobile_scanner/blob/da34970567a64fdf66a7df23963a40bc215d9d18/macos/Classes/MobileScannerPlugin.swift#L190-L205

On Android we handle the method here:
https://github.com/juliansteenbakker/mobile_scanner/blob/da34970567a64fdf66a7df23963a40bc215d9d18/android/src/main/kotlin/dev/steenbakker/mobile_scanner/MobileScannerHandler.kt#L266-L268

Now what is the bug? Well, we forget to call `result(nil)` on MacOS and `result.success(null)` on Android. 🙃 

So for the short term, you could do

```
import 'dart:async';

unawaited(controller.updateScanWindow(rect));
``` 

since the scan window _is actually set_, but we forget to notify that we have done it.

If you feel lucky, a fix is also welcome! Otherwise, I'll probably fix this in the next few days when I find some time.

**Comment by shareefhadid** [comment]
@navaronbracke happy to see you are back to working on this package :) I can wait for the next release, appreciate your work!

**Comment by navaronbracke** [comment]
@shareefhadid This is fixed on the master branch now. This will be included in the next patch release, but I'm probably going to include some other fixes in that release as well (which ones exactly is still on the table :) )
