### ISSUE TITLE
MobileScanner.toggleTorch(_:) EXC_BREAKPOINT

### ISSUE THREAD

**Issue by radivojeostojic** [juliansteenbakker/mobile_scanner#884]
We've been experiencing quite a few crashes on Firebase Crashlytics linked to this bug in the most recent release, version 3.5.2. Has anyone else observed a similar issue?

Here is the screenshot from Crashlytics:
<img width="986" alt="Screenshot 2023-11-28 at 10 30 59" src="https://github.com/juliansteenbakker/mobile_scanner/assets/28922835/00679ccf-0e0b-4c48-aa99-36c06cc4e479">

**Comment by ocakliemre** [comment]
We get the same error in version 3.5.4. app crashes on ios.

![image](https://github.com/juliansteenbakker/mobile_scanner/assets/20604126/eef2eb0b-4f66-42fb-a82b-1c897ce12462)

**Comment by navaronbracke** [comment]
We had issues of this issue in the past. It seems that for some reason, the following line is causing an issue:
https://github.com/juliansteenbakker/mobile_scanner/blob/master/ios/Classes/MobileScanner.swift#L288

However, since that is an assignment only, I don't exactly know why it would crash.

I'd be happy to fix it, but I don't know how just yet.
If anyone has reproduction steps for the crash, that would be greatly appreciated.

**Comment by navaronbracke** [comment]
@radivojeostojic or @ocakliemre Could one of you validate if #886 fixes this bug?
I only made an educated guess as to why it would crash, as I don't have an iOS device to test at the moment.

If it works, I'll prepare a new release with the fix included.

```
dependencies:
 mobile_scanner:
    git:
      url: git@github.com/navaronbracke/mobile_scanner.git
      ref: fix_ios_torch_crash
```

**Comment by radivojeostojic** [comment]
@navaronbracke It does look like it works on my device. I will update the app with this fix to see if it will work for other users.

**Comment by ocakliemre** [comment]
@navaronbracke The problem seems to have been fixed. In our tests on a few users, we did not encounter this error again. Thanks for the quick solution.
