### ISSUE TITLE
crash in iOS 17

### ISSUE THREAD

**Issue by zsrour1991** [juliansteenbakker/mobile_scanner#889]
Exception	NSException *	"-[NSTaggedPointerString containsObject:]: unrecognized selector sent to instance 0x9b83ebd4175bb513"	0x000000028243c810

**Comment by menesty** [comment]
This part  MobileScanner 
// Open the camera device
        if #available(iOS 13.0, *) {
            device = AVCaptureDevice.DiscoverySession(deviceTypes: [.builtInTripleCamera, .builtInDualWideCamera, .builtInDualCamera, .builtInWideAngleCamera], mediaType: .video, position: cameraPosition).devices.first
        }

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTaggedPointerString containsObject:]: unrecognized selector sent to instance 0x9039bb198ba2d9a1'
*** First throw call stack:
(0x1a713c870 0x19f457c00 0x1a71cd19c 0x1a7081ff8 0x1a71c2b10 0x1c35b2680 0x1049e2b34 0x1049e4690 0x1c356f91c 0x1c35b0c80 0x1049e2b34 0x1049e4690 0x1c3560a8c 0x1c35d17e8 0x1c355327c 0x1c3552cac 0x1c3552af4 0x1c3552a38 0x1032e5fc8 0x1032e4474 0x1032f0ae4 0x1032ef220 0x1032ef848 0x107c01374 0x10765d488 0x1049e0f50 0x1049e2b34 0x1049f2fec 0x1049f2ba0 0x1a708720c 0x1a7083f18 0x1a7083668 0x1ea44e5ec 0x1a94a02b4 0x1a949f8f0 0x1029885e0 0x1c9ad6dcc)
libc++abi: terminating due to uncaught exception of type NSException

**Comment by navaronbracke** [comment]
Does it report which selector is not recognised?

**Comment by zsrour1991** [comment]
in this part " .DiscoverySession"

**Comment by navaronbracke** [comment]
That was not what I was asking exactly. Which `deviceType` in the `deviceTypes` of

```
AVCaptureDevice.DiscoverySession(deviceTypes: [...])
```

is the selector that is crashing?

**Comment by zsrour1991** [comment]
yes yes

**Comment by menesty** [comment]
strange thinks, when remove plugin, clear project  flutter clean, rebuild, add again plugin rebuild - then it start work without crash

**Comment by navaronbracke** [comment]
I think I know what the problem is, though. We do not check if the camera device _supports_ the given camera direction.

That is probably the reason why the camera selector is unsupported.

**Comment by navaronbracke** [comment]
@zsrour1991 or @menesty could one of you validate if #896 fixes the crash? I do not have an iOS 17 device yet so I cannot test it at the moment.

Use the following as a dependency in your pubspec.yaml to test it:

```
dependencies:
 mobile_scanner:
    git:
      url: git@github.com:navaronbracke/mobile_scanner.git
      ref: fix_ios_17_camera_crash
```

**Comment by menesty** [comment]
I have test, confirm no crash
