### ISSUE TITLE
Camera still active even if scanner widget is not visible.

### ISSUE THREAD

**Issue by alexIvantsov** [juliansteenbakker/mobile_scanner#951]
Hello.
Thanks for this great package!

There is one case I'm trying to resolve:
If QR code is scanned - redirect a user to the next screen.
If I push the next screen, the scanner is still active.
I've tried to stop the scanner like this:
```
  @override
  void didPushNext() {
    controller.stop();
  }
```

It solves the problem and the scanner is inactive if another screen is on top.
But If the app goes in the background, and then comes back to the foreground `didChangeAppLifecycleState` is fired and the scanner becomes active again even if the scanner is not visible (because it is covered by another screen).

Unfortunately, I can't just replace the scanner with the next screen because I want to have the ability to come back to that screen.

To resolve this issue I  do `CustomController(autoStart: false)` and handle the lifecycle manually. 
But in this case, I also need to take care of exceptions that might occur during the `controller.start`, 
and my `didChangeAppLifecycleState` method looks like duplicated from the library.

Could you advise if there is a better way to resolve this issue?

**Comment by apinilabs-pascal** [comment]
@navaronbracke issue is even in the example app. please have the example updated how to successfully release camera.

**Comment by apinilabs-pascal** [comment]
> @apinilabs-pascal The example app already includes samples on how to manage the lifecycle of the controller.

I just pulled the latest code and tried. There seems still something wrong with it since other 3rd party camera apps/packages or the shipped camera app on the Android phone does not cause the same issues as we have with the mobile_scanner. 

Edit: found the issue. the observer of the WidgetBinding is removed already when leaving the scanner with controller view. Then it's obviously never call the didChangeAppLifecycleState. If I pause the app while scanner is open it works fine.
So just a setup issue to be aware of. I'm good then.

**Comment by navaronbracke** [comment]
Yes, if the State's `dispose()` is called, you'll usually destroy the widgets binding observer, because it is tied to that widget's state. But the widget binding observer - which is the class that mixes in `with WidgetsBindingObserver` - can be any class. Maybe you'd want not the widget but some higher up class to do the observing.

**Comment by navaronbracke** [comment]
Per https://github.com/juliansteenbakker/mobile_scanner/issues/951#issuecomment-2340877999 I'm going to close this issue.
