### ISSUE TITLE
toggleTorch not working properly on mobile web versions

### ISSUE THREAD

**Issue by WieFel** [juliansteenbakker/mobile_scanner#955]
First of all, thanks for the awesome package! It's incredible that it works on so many platforms out of the box!

I just have a tiny problem: I have a simple qr-code scanner implemented using Flutter web, and on the following platforms/browsers I experienced problems with `controller.toggleTorch()`:

**Android 14 (Google Pixel 8)**
- Chrome(121.0.6167.164): Turning on the torch works, but toggling it again (i.e. switching it off) just doesn't do anything.
- Firefox (122.0.1): Turning on the torch doesn't have any effect. It won't turn on. The call of `controller.toggleTorch()` seems to have no effect at all.

**iOS 15.7.9 (iPhone SE)**
- Safari: Turning on the torch doesn't have any effect. It won't turn on.

Unfortunately, I cannot provide debug logs in this case, as I am not able to attach a debugger to the mobile web version of my Flutter app.

Running Flutter `3.16.9` and mobile_scanner version `4.0.0`.

**Comment by navaronbracke** [comment]
Thanks for the report.

When it comes to features on the web, it very much depends on the browsers and/or supported features by the specific `MediaStreamTrack`. Since I can't test the web version on an emulator, would you be willing to inspect the following?

(My goal would be to figure out what capabilities we _do_ have)

1) Create a new Flutter app, that supports the web
2) Import 'package:web' (the new style of JS interop)
3) Let it get the user media and request a video track (to get the camera running) You can take look at my WIP branch here
https://github.com/navaronbracke/mobile_scanner/tree/mobile_scanner_platform_interface for the new web code for the camera
4) Call getSettings() and getCapabilities() on the MediaStreamTrack
5) Using `objectKeys()` from `dart:js_util` inspect the actual JS object keys on the Javascript objects for both the settings and capabilities (in my experience, the capabilities should be enough already, you will probably see the same result) 
6) Once you get the object keys for the capabilities, post them here in a reply

I think there's something weird going on with a) the old style dart:html interop or b) the capabilities of the track itself
I do agree, we need an API to detect if camera features are supported

**Comment by navaronbracke** [comment]
It turns out the torch is only for image tracks and not video tracks.

See https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints#instance_properties_of_video_tracks and the image tracks section above the video tracks.
