### ISSUE TITLE
 FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':mobile_scanner:compileDebugJavaWithJavac'. > error: invalid source release: 17

### ISSUE THREAD

**Issue by Fariqofficial** [juliansteenbakker/mobile_scanner#996]
I got an error message:

"FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':mobile_scanner:compileDebugJavaWithJavac'.
> error: invalid source release: 17"

When I run my project in visual studio code, I have also used jdk version 17 but when I run it again, I still get the same error message.

![Screenshot_3](https://github.com/juliansteenbakker/mobile_scanner/assets/37206465/728c5aeb-7c1d-444d-9c26-b46b5e8aa437)

**Comment by KyoheiG3** [comment]
See #922 and #957.

**Comment by huangsir0** [comment]
any update?

**Comment by navaronbracke** [comment]
As noted above, using Java 17 is required from version 4.0.0 onwards. We will document this requirement better when addressing #922

**Comment by EhabSalah** [comment]
Any updates?

**Comment by navaronbracke** [comment]
@EhabSalah There are no real updates, because there is nothing that the `mobile_scanner` package can do.

The only thing that we can provide is asking you to update to Java 17.
If you are using the Java installation from Android Studio, update to Android Studio "Flamingo" or higher.
If you are using a standalone Java version, update that Java version to Java 17.
If you are using CI/CD, use a CI/CD pipeline that has Java 17 available, _and enable the Java 17 version in the CI/CD settings_
